markdown: kramdown
highlighter: rouge
# paginate: 10
permalink: /:categories/:year/:month/:day/:title/

name: Chimeces
url: http://chimeces.com

kramdown:
  input: GFM
  hard_wrap: false

redcarpet:
  extensions: [fenced_code_blocks, tables, autolink, no_intra_emphasis, strikethrough]

