markdown: kramdown
highlighter: pygments
pygments: true
paginate: 10
permalink: /:categories/:year/:month/:day/:title/

name: Chimeces
url: http://chimeces.com

kramdown:
  input: GFM
  use_coderay: true
