markdown: redcarpet
highlighter: pygments
paginate: 10
permalink: /:categories/:year/:month/:day/:title/

name: Chimeces
url: http://chimeces.com

redcarpet: [fenced_code_blocks, tables, autolink, no_intra_emphasis, strikethrough]
